site_name: 100 Site Architecture
site_url: https://100AutomationsArchitecture.com/
nav:
    - Welcome: index.md
    - Getting started: gettingstarted.md
    - Code: code.md
    - Code: code.md
theme: readthedocs
extra_css:
    - index.css
