site_name: 100 Automations-Site Architecture
site_url: https://100automations.github.io/Architecture/
repo_url: https://github.com/100Automations/Architecture
edit_uri: edit/main/docs

nav: 
  - Home: index.md
  - Site: site.md
  - Front-End:
    - Folders: Front-End/index.md
    - assets/: Front-End/assets/index.md
    - HTML:
      - _includes/: Front-End/_includes/index.md
      - _layouts/: Front-End/_layouts/index.md
    - _sass/: Front-End/_sass/index.md
  - Back-End:
    - Folders: Back-End/index.md
    - _data/: Back-End/data/index.md 
    - _config.yml: Back-End/config/index.md
    - Collections: Back-End/collections/index.md
